// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOO-KYdo5zQtdaSlbWrKVVUHVRhiD_ShM',
    appId: '1:793414812346:web:4a29564bd0b1b48ba0b883',
    messagingSenderId: '793414812346',
    projectId: 'fr-style-9b4b3',
    authDomain: 'fr-style-9b4b3.firebaseapp.com',
    storageBucket: 'fr-style-9b4b3.firebasestorage.app',
    measurementId: 'G-7VF6P6BS8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4cIyuzpkd7DXYqzYYU51Ukgo8ivsWyhM',
    appId: '1:793414812346:android:ef641626ba6d90cfa0b883',
    messagingSenderId: '793414812346',
    projectId: 'fr-style-9b4b3',
    storageBucket: 'fr-style-9b4b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dFWBifPIJq2Es3kpxM2BDhxmqQikoeE',
    appId: '1:793414812346:ios:0f943f0c169bcea7a0b883',
    messagingSenderId: '793414812346',
    projectId: 'fr-style-9b4b3',
    storageBucket: 'fr-style-9b4b3.firebasestorage.app',
    iosBundleId: 'com.example.frTyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dFWBifPIJq2Es3kpxM2BDhxmqQikoeE',
    appId: '1:793414812346:ios:0f943f0c169bcea7a0b883',
    messagingSenderId: '793414812346',
    projectId: 'fr-style-9b4b3',
    storageBucket: 'fr-style-9b4b3.firebasestorage.app',
    iosBundleId: 'com.example.frTyle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOO-KYdo5zQtdaSlbWrKVVUHVRhiD_ShM',
    appId: '1:793414812346:web:e0af3db4d3f7104ba0b883',
    messagingSenderId: '793414812346',
    projectId: 'fr-style-9b4b3',
    authDomain: 'fr-style-9b4b3.firebaseapp.com',
    storageBucket: 'fr-style-9b4b3.firebasestorage.app',
    measurementId: 'G-CDF82KG451',
  );
}
