import 'dart:async';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/order_model.dart';
import '../models/cart_model.dart';
import '../services/order_service.dart';

class OrderProvider extends ChangeNotifier {
  final OrderService _orderService = OrderService();
  final List<OrderModel> _orders = [];
  StreamSubscription<List<OrderModel>>? _ordersSubscription;
  StreamSubscription<User?>? _authSubscription;

  OrderProvider() {
    _authSubscription = FirebaseAuth.instance.authStateChanges().listen((user) {
      _ordersSubscription?.cancel();
      if (user != null) {
        _ordersSubscription = _orderService.getUserOrders().listen((orders) {
          _orders.clear();
          _orders.addAll(orders);
          notifyListeners();
        }, onError: (error) {
          debugPrint('Error loading orders: $error');
        });
      } else {
        _orders.clear();
        notifyListeners();
      }
    });
  }

  @override
  void dispose() {
    _ordersSubscription?.cancel();
    _authSubscription?.cancel();
    super.dispose();
  }

  List<OrderModel> get orders => List.unmodifiable(_orders);

  List<OrderModel> get activeOrders => _orders.where((o) => o.status != 'delivered' && o.status != 'cancelled').toList();
  List<OrderModel> get historyOrders => _orders.where((o) => o.status == 'delivered').toList();
  List<OrderModel> get cancelledOrders => _orders.where((o) => o.status == 'cancelled').toList();

  Future<void> placeOrder({
    required List<CartItem> items,
    required Map<String, dynamic> shippingAddress,
    required String paymentMethod,
    required double subtotal,
    required double shippingFee,
    required double total,
  }) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) throw Exception('Must be logged in to place an order');

    final newOrder = OrderModel(
      id: '', // Generated by Firestore
      userId: user.uid,
      items: items,
      shippingAddress: shippingAddress,
      paymentMethod: paymentMethod,
      subtotal: subtotal,
      shippingFee: shippingFee,
      total: total,
      status: 'processing',
      createdAt: DateTime.now(),
    );

    await _orderService.createOrder(newOrder);
    notifyListeners();
  }
}
